name = "svu-serienbrief-worker"
main = "src/index.ts"
compatibility_date = "2024-12-25"

[[d1_databases]]
binding = "svu_prod"
database_name = "svu-prod"
database_id = "dc2cfc65-6242-4af4-bf37-ce5d7e3f6330"