name = "svu-verification-worker"
main = "src/index.ts"
compatibility_date = "2024-12-25"

[placement]
mode = "smart"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

[[routes]]
pattern = "svu-mitgliedschaft.untereuerheim.com"
custom_domain = true

[[d1_databases]]
binding = "svu_prod01"
database_name = "svu-prod01"
database_id = "d9a3103d-a1fd-4260-b6c2-cf3d7530d956"